version: '3.8'
services:
  mongo:
    image: mongo:7.0.5
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.13.3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: "12345678"